### ISSUE TITLE
What font are you using in the README.md demo?

### ISSUE THREAD

**Issue by Utagai** [OrangeFran/navigator#1]
Found this from your contribution to spotify-tui. I really dig that font you're using in the demo. Curious to know if you have the name.

You didn't have any other contact information so this was the only way I could ask. :slightly_smiling_face:

**Comment by OrangeFran** [comment]
It's the Fantasque Sans font. Definetely one of my favourites.[GitHub Repo](https://github.com/belluzj/fantasque-sans)

**Comment by Utagai** [comment]
Thanks! I had seen this font before but could not remember the name.

Closing.
